# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PPL_sigmoid <- function(btj, j, X, Y, S, Z, Kmat, h1, tau0, tau1) {
    .Call(`_TrajecEstm_PPL_sigmoid`, btj, j, X, Y, S, Z, Kmat, h1, tau0, tau1)
}

estimate_beta_theta_lbfgs_V1 <- function(j, X, Y_S, S, Z, Kmat, tau0, tau1, tau_norm, sce, init, tol = 1e-8, max_iter = 1000L, center) {
    .Call(`_TrajecEstm_estimate_beta_theta_lbfgs_V1`, j, X, Y_S, S, Z, Kmat, tau0, tau1, tau_norm, sce, init, tol, max_iter, center)
}

estimate_beta_theta_lbfgs_V2 <- function(j, X, Y_S, S, Z, Kmat, tau0, tau1, tau_norm, sce, init, tol = 1e-8, max_iter = 1000L, center) {
    .Call(`_TrajecEstm_estimate_beta_theta_lbfgs_V2`, j, X, Y_S, S, Z, Kmat, tau0, tau1, tau_norm, sce, init, tol, max_iter, center)
}

estimate_beta_NP <- function(j, X, Y_S, S, Z, Kmat, d, tau0, tau1, init, tol = 1e-8, max_iter = 1000L) {
    .Call(`_TrajecEstm_estimate_beta_NP`, j, X, Y_S, S, Z, Kmat, d, tau0, tau1, init, tol, max_iter)
}

mu_r <- function(j, t, s, h, btj, X, Y, delPi, S, Z, sce, tau_norm, center) {
    .Call(`_TrajecEstm_mu_r`, j, t, s, h, btj, X, Y, delPi, S, Z, sce, tau_norm, center)
}

mu_r_core <- function(t, s, h, btj, X, Y, S, Z, sce, tau_norm, center) {
    .Call(`_TrajecEstm_mu_r_core`, t, s, h, btj, X, Y, S, Z, sce, tau_norm, center)
}

mu_NP <- function(j, t, s, h1, h2, bj, X, Y, delPi, S, Z) {
    .Call(`_TrajecEstm_mu_NP`, j, t, s, h1, h2, bj, X, Y, delPi, S, Z)
}

mu_surv <- function(s, h, beta, X, Y, S, Z, tau) {
    .Call(`_TrajecEstm_mu_surv`, s, h, beta, X, Y, S, Z, tau)
}

mu_surv_core <- function(s, h, beta, X, Y, S) {
    .Call(`_TrajecEstm_mu_surv_core`, s, h, beta, X, Y, S)
}

estimate_beta_survivor_lbfgs <- function(X, Y, S, Kmat, tau0, tau1, init, tol = 1e-8, max_iter = 1000L) {
    .Call(`_TrajecEstm_estimate_beta_survivor_lbfgs`, X, Y, S, Kmat, tau0, tau1, init, tol, max_iter)
}

matK_tri4 <- function(Z, h) {
    .Call(`_TrajecEstm_matK_tri4`, Z, h)
}

matK_tri4_loop <- function(Z, S, h) {
    .Call(`_TrajecEstm_matK_tri4_loop`, Z, S, h)
}

matK <- function(Z, h1) {
    .Call(`_TrajecEstm_matK`, Z, h1)
}

matK_sparse <- function(Z, h1) {
    .Call(`_TrajecEstm_matK_sparse`, Z, h1)
}

matK_dispatch <- function(Z, h1, use_sparse) {
    .Call(`_TrajecEstm_matK_dispatch`, Z, h1, use_sparse)
}

compute_r_scalar <- function(s, t, theta, sce, tau, center) {
    .Call(`_TrajecEstm_compute_r_scalar`, s, t, theta, sce, tau, center)
}

compute_r_vec <- function(s, t, theta, sce, tau, center) {
    .Call(`_TrajecEstm_compute_r_vec`, s, t, theta, sce, tau, center)
}

compute_r_dr <- function(s, t, theta, sce, tau, center) {
    .Call(`_TrajecEstm_compute_r_dr`, s, t, theta, sce, tau, center)
}

gradi <- function(btj, j, X, Y_A, A, Z, Kmat, h1, tau0, tau1) {
    .Call(`_TrajecEstm_gradi`, btj, j, X, Y_A, A, Z, Kmat, h1, tau0, tau1)
}

rfun <- function(a, t, theta) {
    .Call(`_TrajecEstm_rfun`, a, t, theta)
}

rfun2 <- function(a, t, theta) {
    .Call(`_TrajecEstm_rfun2`, a, t, theta)
}

